// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TreasuryContract$Type } from "./TreasuryContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TreasuryContract"]: TreasuryContract$Type;
    ["contracts/TreasuryContract.sol:TreasuryContract"]: TreasuryContract$Type;
  }
}
