// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { DecentralizedBetting$Type } from "./DecentralizedBetting";
import { IMatchNFT$Type } from "./IMatchNFT";
import { ISocialOracle$Type } from "./ISocialOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DecentralizedBetting"]: DecentralizedBetting$Type;
    ["IMatchNFT"]: IMatchNFT$Type;
    ["ISocialOracle"]: ISocialOracle$Type;
    ["contracts/DecentralizedBetting.sol:DecentralizedBetting"]: DecentralizedBetting$Type;
    ["contracts/DecentralizedBetting.sol:IMatchNFT"]: IMatchNFT$Type;
    ["contracts/DecentralizedBetting.sol:ISocialOracle"]: ISocialOracle$Type;
  }
}
