// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC20Burnable$Type } from "./ERC20Burnable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Burnable"]: ERC20Burnable$Type;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol:ERC20Burnable"]: ERC20Burnable$Type;
  }
}
