// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IStakeContract$Type } from "./IStakeContract";
import { MockStakeContract$Type } from "./MockStakeContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IStakeContract"]: IStakeContract$Type;
    ["MockStakeContract"]: MockStakeContract$Type;
    ["contracts/MockStakeContract.sol:IStakeContract"]: IStakeContract$Type;
    ["contracts/MockStakeContract.sol:MockStakeContract"]: MockStakeContract$Type;
  }
}
