// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TestLiquidityToken$Type } from "./TestLiquidityToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestLiquidityToken"]: TestLiquidityToken$Type;
    ["contracts/TEST_LiqudityToken.sol:TestLiquidityToken"]: TestLiquidityToken$Type;
  }
}
