// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TEST_LiqudityToken$Type } from "./TEST_LiqudityToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TEST_LiqudityToken"]: TEST_LiqudityToken$Type;
    ["contracts/TEST_LiqudityToken.sol:TEST_LiqudityToken"]: TEST_LiqudityToken$Type;
  }
}
