// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TEST_StakingToken$Type } from "./TEST_StakingToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TEST_StakingToken"]: TEST_StakingToken$Type;
    ["contracts/TEST_StakingToken.sol:TEST_StakingToken"]: TEST_StakingToken$Type;
  }
}
