// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TestStakingToken$Type } from "./TestStakingToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestStakingToken"]: TestStakingToken$Type;
    ["contracts/TEST_StakingToken.sol:TestStakingToken"]: TestStakingToken$Type;
  }
}
