// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IStakeContract$Type } from "./IStakeContract";
import { SocialOracle$Type } from "./SocialOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IStakeContract"]: IStakeContract$Type;
    ["SocialOracle"]: SocialOracle$Type;
    ["contracts/SocialOracle.sol:IStakeContract"]: IStakeContract$Type;
    ["contracts/SocialOracle.sol:SocialOracle"]: SocialOracle$Type;
  }
}
