// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BetStakingToken$Type } from "./BetStakingToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BetStakingToken"]: BetStakingToken$Type;
    ["contracts/BetStakingToken.sol:BetStakingToken"]: BetStakingToken$Type;
  }
}
