// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Address$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Address",
  "sourceName": "@openzeppelin/contracts/utils/Address.sol",
  "abi": [],
  "bytecode": "0x608060405234601a57604051603f6020823930815050603f90f35b600080fdfe6080604052600080fdfea264697066735822122025323c4429d8494a91834445a80ff2a99aaa94416cd3f7c041e5fb4b854cab1964736f6c63430008180033",
  "deployedBytecode": "0x6080604052600080fdfea264697066735822122025323c4429d8494a91834445a80ff2a99aaa94416cd3f7c041e5fb4b854cab1964736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Address",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Address$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Address.sol:Address",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Address$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Address",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Address$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Address.sol:Address",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Address$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Address",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Address$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Address.sol:Address",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Address$Type["abi"]>>;
}
