// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MatchNFT$Type } from "./MatchNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MatchNFT"]: MatchNFT$Type;
    ["contracts/MatchNFT.sol:MatchNFT"]: MatchNFT$Type;
  }
}
